M48
; DRILL file {KiCad 6.0.10+dfsg-1~bpo11+1} date St 1. února 2023, 20:55:50
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-01T20:55:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.1Y-5.75
X3.5Y-4.25
X4.0Y-5.75
X4.3Y-5.75
X5.1Y-5.75
X5.4Y-5.75
X5.8Y-4.25
X6.2Y-5.75
T0
M30
